paths:
  train_manifest: path/to/train.jsonl
  test_manifest: path/to/test.jsonl
  save_dir: ./save_dir
  tokenizer_path: path/to/tokenizer.model

training:
  epochs: 20
  seed: 42
  checkpoint_dir: checkpoints

dataloader:
  batch_size: 16
  num_workers: 0

optimizer:
  lr: 1e-3
  type: adam # Only Adam is supported for reward model training at the moment

scheduler:
  use: false
  type: steplr
  step_size: 30
  gamma: 0.8

model:
  embed_dim: 128
  hidden_dim: 256
  lstm_layers: 1
  audio_conv_channels: 128
  audio_conv_layers: 3
  head_hidden: 256
  dropout: 0.3

preprocessor:
  normalize: per_feature
  window_size: 0.02
  sample_rate: 16000
  window_stride: 0.01
  window: hann
  features: 64
  n_fft: 512
  frame_splicing: 1
  dither: 1.0e-05
  stft_conv: false
