model:
  name: "RobotsMali/soloni-114m-tdt-ctc-v0"
  first_training: True

tokenizer:
  path: "tokenizers/lau-tokenizer"
  type: "bpe"

data_loaders:
  train:
    manifest_filepath: "./jeli-asr/original-train-manifest.jsonl"
    sample_rate: 16000
    max_duration: 30
    min_duration: 0.1
    batch_size: 64  # smaller batch
    num_workers: 8
    shuffle: True
    pin_memory: True
  valid:
    manifest_filepath: "./jeli-asr/original-test-manifest.jsonl"  # Path to the validation manifest
    sample_rate: 16000
    max_duration: 10
    batch_size: 32
    num_workers: 8
    shuffle: False
    pin_memory: True
  test:
    manifest_filepath: "./jeli-asr/original-test-manifest.jsonl" # Path to the test manifest
    sample_rate: 16000
    max_duration: 30
    batch_size: 32
    num_workers: 8
    shuffle: False
    pin_memory: True

wandb:
  project: "lau-train" # Ensure this matches your WandB project name
  name: "soloni-lau-v1.0.0" # Ensure this is unique for each run

optim:
  name: "adamw"
  # Slightly lower LR if unfreezing
  lr: 2
  betas: [0.9, 0.98]
  weight_decay: 1e-4
  sched:
    name: "NoamAnnealing"
    max_steps: 11800  # (epochs * steps_per_epoch)
    warmup_steps: 1000
    warmup_ratio: null
    d_model: 512 # only for NoamAnnealing scheduler
    min_lr: 1e-6
    last_epoch: -1


training:
  # freezing the encoder
  freeze_encoder: False
  precision: "bf16-mixed"
  checkpoint_dir: "./checkpoints/${wandb.name}"
  save_top_k: 1
  patience: 20  # more patience
  epochs: 100
  accumulate_grad_batches: 1  # effective batch size 32 * 4
  check_val_every_n_epoch: 1
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  save_model_path: "models/${wandb.name}.nemo"
