training:
  seed: 42
  device: auto
  precision: fp32
  clip_eps: 0.2
  actor_lr: 1.0e-03
  critic_lr: 0.001
  epochs: 5
  K_updates: 3
  save_dir: ./rlnf_runs/exp01
  pin_memory: false

paths:
  tokenizer_path: /path/to/tokenizer.model
  reward_path: /path/to/reward_model.rw

wandb:
  enable: true
  project: rlnf
  run_name: exp01

model:
  name: RobotsMali/stt-bm-quartznet15x5-V0
  vocab: null

critic:
  hidden_dim: 128
  layers: 2
  dropout: 0.1

data:
  train_manifest: path/to/train_manifest.jsonl
  valid_manifest: path/to/valid_manfest.jsonl
  batch_size: 4
  num_workers: 0 # Keep to zero if using GPU (current implemenation doesn't support parallelism)

preprocessor:
  normalize: per_feature
  window_size: 0.02
  sample_rate: 16000
  window_stride: 0.01
  window: hann
  features: 64
  n_fft: 512
  frame_splicing: 1
  dither: 1.0e-05
  stft_conv: false
